/* CVS $Id: $ */
package uk.ac.bristol.dundry.vocabs; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from file:////home/pldms/Development/Projects/2012/data.bris/dundry/src/main/resources/common/vocabs/bibo.xml.owl 
 * @author Auto-generated by schemagen on 26 Sep 2012 11:14 
 */
public class Bibo {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/ontology/bibo/";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "http://purl.org/ontology/bibo/1.3/";
    
    /** <p>A summary of the resource.</p> */
    public static final Property abstract_ = m_model.createProperty( "http://purl.org/ontology/bibo/abstract" );
    
    /** <p>A legal decision that affirms a ruling.</p> */
    public static final Property affirmedBy = m_model.createProperty( "http://purl.org/ontology/bibo/affirmedBy" );
    
    /** <p>Critical or explanatory note for a Document.</p> */
    public static final Property annotates = m_model.createProperty( "http://purl.org/ontology/bibo/annotates" );
    
    /** <p>The date on which a legal case is argued before a court. Date is of format 
     *  xsd:date</p>
     */
    public static final Property argued = m_model.createProperty( "http://purl.org/ontology/bibo/argued" );
    
    public static final Property asin = m_model.createProperty( "http://purl.org/ontology/bibo/asin" );
    
    /** <p>An ordered list of authors. Normally, this list is seen as a priority list 
     *  that order authors by importance.</p>
     */
    public static final Property authorList = m_model.createProperty( "http://purl.org/ontology/bibo/authorList" );
    
    /** <p>An chapter number</p> */
    public static final Property chapter = m_model.createProperty( "http://purl.org/ontology/bibo/chapter" );
    
    /** <p>Relates a document to another document that cites the first document.</p> */
    public static final Property citedBy = m_model.createProperty( "http://purl.org/ontology/bibo/citedBy" );
    
    /** <p>Relates a document to another document that is cited by the first document 
     *  as reference, comment, review, quotation or for another purpose.</p>
     */
    public static final Property cites = m_model.createProperty( "http://purl.org/ontology/bibo/cites" );
    
    public static final Property coden = m_model.createProperty( "http://purl.org/ontology/bibo/coden" );
    
    /** <p>This property is for a plain-text rendering of the content of a Document. 
     *  While the plain-text content of an entire document could be described by this 
     *  property.</p>
     */
    public static final Property content = m_model.createProperty( "http://purl.org/ontology/bibo/content" );
    
    /** <p>An ordered list of contributors. Normally, this list is seen as a priority 
     *  list that order contributors by importance.</p>
     */
    public static final Property contributorList = m_model.createProperty( "http://purl.org/ontology/bibo/contributorList" );
    
    /** <p>A court associated with a legal document; for example, that which issues a 
     *  decision.</p>
     */
    public static final Property court = m_model.createProperty( "http://purl.org/ontology/bibo/court" );
    
    /** <p>The thesis degree.</p> */
    public static final Property degree = m_model.createProperty( "http://purl.org/ontology/bibo/degree" );
    
    /** <p>A Film director.</p> */
    public static final Property director = m_model.createProperty( "http://purl.org/ontology/bibo/director" );
    
    /** <p>Distributor of a document or a collection of documents.</p> */
    public static final Property distributor = m_model.createProperty( "http://purl.org/ontology/bibo/distributor" );
    
    public static final Property doi = m_model.createProperty( "http://purl.org/ontology/bibo/doi" );
    
    public static final Property eanucc13 = m_model.createProperty( "http://purl.org/ontology/bibo/eanucc13" );
    
    /** <p>The name defining a special edition of a document. Normally its a literal 
     *  value composed of a version number and words.</p>
     */
    public static final Property edition = m_model.createProperty( "http://purl.org/ontology/bibo/edition" );
    
    /** <p>A person having managerial and sometimes policy-making responsibility for 
     *  the editorial part of a publishing firm or of a newspaper, magazine, or other 
     *  publication.</p>
     */
    public static final Property editor = m_model.createProperty( "http://purl.org/ontology/bibo/editor" );
    
    /** <p>An ordered list of editors. Normally, this list is seen as a priority list 
     *  that order editors by importance.</p>
     */
    public static final Property editorList = m_model.createProperty( "http://purl.org/ontology/bibo/editorList" );
    
    public static final Property eissn = m_model.createProperty( "http://purl.org/ontology/bibo/eissn" );
    
    public static final Property gtin14 = m_model.createProperty( "http://purl.org/ontology/bibo/gtin14" );
    
    public static final Property handle = m_model.createProperty( "http://purl.org/ontology/bibo/handle" );
    
    public static final Property identifier = m_model.createProperty( "http://purl.org/ontology/bibo/identifier" );
    
    /** <p>An agent that is interviewed by another agent.</p> */
    public static final Property interviewee = m_model.createProperty( "http://purl.org/ontology/bibo/interviewee" );
    
    /** <p>An agent that interview another agent.</p> */
    public static final Property interviewer = m_model.createProperty( "http://purl.org/ontology/bibo/interviewer" );
    
    public static final Property isbn = m_model.createProperty( "http://purl.org/ontology/bibo/isbn" );
    
    public static final Property isbn10 = m_model.createProperty( "http://purl.org/ontology/bibo/isbn10" );
    
    public static final Property isbn13 = m_model.createProperty( "http://purl.org/ontology/bibo/isbn13" );
    
    public static final Property issn = m_model.createProperty( "http://purl.org/ontology/bibo/issn" );
    
    /** <p>An issue number</p> */
    public static final Property issue = m_model.createProperty( "http://purl.org/ontology/bibo/issue" );
    
    /** <p>An entity responsible for issuing often informally published documents such 
     *  as press releases, reports, etc.</p>
     */
    public static final Property issuer = m_model.createProperty( "http://purl.org/ontology/bibo/issuer" );
    
    public static final Property lccn = m_model.createProperty( "http://purl.org/ontology/bibo/lccn" );
    
    /** <p>A description (often numeric) that locates an item within a containing document 
     *  or collection.</p>
     */
    public static final Property locator = m_model.createProperty( "http://purl.org/ontology/bibo/locator" );
    
    /** <p>The number of pages contained in a document</p> */
    public static final Property numPages = m_model.createProperty( "http://purl.org/ontology/bibo/numPages" );
    
    /** <p>The number of volumes contained in a collection of documents (usually a series, 
     *  periodical, etc.).</p>
     */
    public static final Property numVolumes = m_model.createProperty( "http://purl.org/ontology/bibo/numVolumes" );
    
    /** <p>A generic item or document number. Not to be confused with issue number.</p> */
    public static final Property number = m_model.createProperty( "http://purl.org/ontology/bibo/number" );
    
    public static final Property oclcnum = m_model.createProperty( "http://purl.org/ontology/bibo/oclcnum" );
    
    /** <p>The organizer of an event; includes conference organizers, but also government 
     *  agencies or other bodies that are responsible for conducting hearings.</p>
     */
    public static final Property organizer = m_model.createProperty( "http://purl.org/ontology/bibo/organizer" );
    
    /** <p>Owner of a document or a collection of documents.</p> */
    public static final Property owner = m_model.createProperty( "http://purl.org/ontology/bibo/owner" );
    
    /** <p>Ending page number within a continuous page range.</p> */
    public static final Property pageEnd = m_model.createProperty( "http://purl.org/ontology/bibo/pageEnd" );
    
    /** <p>Starting page number within a continuous page range.</p> */
    public static final Property pageStart = m_model.createProperty( "http://purl.org/ontology/bibo/pageStart" );
    
    /** <p>A string of non-contiguous page spans that locate a Document within a Collection. 
     *  Example: 23-25, 34, 54-56. For continuous page ranges, use the pageStart and 
     *  pageEnd properties.</p>
     */
    public static final Property pages = m_model.createProperty( "http://purl.org/ontology/bibo/pages" );
    
    public static final Property performer = m_model.createProperty( "http://purl.org/ontology/bibo/performer" );
    
    public static final Property pmid = m_model.createProperty( "http://purl.org/ontology/bibo/pmid" );
    
    /** <p>The prefix of a name</p> */
    public static final Property prefixName = m_model.createProperty( "http://purl.org/ontology/bibo/prefixName" );
    
    /** <p>Relates a document to an event; for example, a paper to a conference.</p> */
    public static final Property presentedAt = m_model.createProperty( "http://purl.org/ontology/bibo/presentedAt" );
    
    /** <p>Relates an event to associated documents; for example, conference to a paper.</p> */
    public static final Property presents = m_model.createProperty( "http://purl.org/ontology/bibo/presents" );
    
    /** <p>Producer of a document or a collection of documents.</p> */
    public static final Property producer = m_model.createProperty( "http://purl.org/ontology/bibo/producer" );
    
    /** <p>An agent that receives a communication document.</p> */
    public static final Property recipient = m_model.createProperty( "http://purl.org/ontology/bibo/recipient" );
    
    /** <p>The resource in which another resource is reproduced.</p> */
    public static final Property reproducedIn = m_model.createProperty( "http://purl.org/ontology/bibo/reproducedIn" );
    
    /** <p>A legal decision that reverses a ruling.</p> */
    public static final Property reversedBy = m_model.createProperty( "http://purl.org/ontology/bibo/reversedBy" );
    
    /** <p>Relates a review document to a reviewed thing (resource, item, etc.).</p> */
    public static final Property reviewOf = m_model.createProperty( "http://purl.org/ontology/bibo/reviewOf" );
    
    /** <p>A section number</p> */
    public static final Property section = m_model.createProperty( "http://purl.org/ontology/bibo/section" );
    
    public static final Property shortDescription = m_model.createProperty( "http://purl.org/ontology/bibo/shortDescription" );
    
    /** <p>The abbreviation of a title.</p> */
    public static final Property shortTitle = m_model.createProperty( "http://purl.org/ontology/bibo/shortTitle" );
    
    public static final Property sici = m_model.createProperty( "http://purl.org/ontology/bibo/sici" );
    
    /** <p>The publication status of (typically academic) content.</p> */
    public static final Property status = m_model.createProperty( "http://purl.org/ontology/bibo/status" );
    
    /** <p>A legal decision on appeal that takes action on a case (affirming it, reversing 
     *  it, etc.).</p>
     */
    public static final Property subsequentLegalDecision = m_model.createProperty( "http://purl.org/ontology/bibo/subsequentLegalDecision" );
    
    /** <p>The suffix of a name</p> */
    public static final Property suffixName = m_model.createProperty( "http://purl.org/ontology/bibo/suffixName" );
    
    /** <p>Relates a document to some transcribed original.</p> */
    public static final Property transcriptOf = m_model.createProperty( "http://purl.org/ontology/bibo/transcriptOf" );
    
    /** <p>Relates a translated document to the original document.</p> */
    public static final Property translationOf = m_model.createProperty( "http://purl.org/ontology/bibo/translationOf" );
    
    /** <p>A person who translates written document from one language to another.</p> */
    public static final Property translator = m_model.createProperty( "http://purl.org/ontology/bibo/translator" );
    
    public static final Property upc = m_model.createProperty( "http://purl.org/ontology/bibo/upc" );
    
    /** <p>Universal Resource Identifier of a document</p> */
    public static final Property uri = m_model.createProperty( "http://purl.org/ontology/bibo/uri" );
    
    /** <p>A volume number</p> */
    public static final Property volume = m_model.createProperty( "http://purl.org/ontology/bibo/volume" );
    
    /** <p>A scholarly academic article, typically published in a journal.</p> */
    public static final Resource AcademicArticle = m_model.createResource( "http://purl.org/ontology/bibo/AcademicArticle" );
    
    /** <p>A written composition in prose, usually nonfiction, on a specific topic, forming 
     *  an independent part of a book or other publication, as a newspaper or magazine.</p>
     */
    public static final Resource Article = m_model.createResource( "http://purl.org/ontology/bibo/Article" );
    
    /** <p>An audio document; aka record.</p> */
    public static final Resource AudioDocument = m_model.createResource( "http://purl.org/ontology/bibo/AudioDocument" );
    
    /** <p>An audio-visual document; film, video, and so forth.</p> */
    public static final Resource AudioVisualDocument = m_model.createResource( "http://purl.org/ontology/bibo/AudioVisualDocument" );
    
    /** <p>Draft legislation presented for discussion to a legal body.</p> */
    public static final Resource Bill = m_model.createResource( "http://purl.org/ontology/bibo/Bill" );
    
    /** <p>A written or printed work of fiction or nonfiction, usually on sheets of paper 
     *  fastened or bound together within covers.</p>
     */
    public static final Resource Book = m_model.createResource( "http://purl.org/ontology/bibo/Book" );
    
    /** <p>A section of a book.</p> */
    public static final Resource BookSection = m_model.createResource( "http://purl.org/ontology/bibo/BookSection" );
    
    /** <p>A written argument submitted to a court.</p> */
    public static final Resource Brief = m_model.createResource( "http://purl.org/ontology/bibo/Brief" );
    
    /** <p>A chapter of a book.</p> */
    public static final Resource Chapter = m_model.createResource( "http://purl.org/ontology/bibo/Chapter" );
    
    /** <p>A collection of statutes.</p> */
    public static final Resource Code = m_model.createResource( "http://purl.org/ontology/bibo/Code" );
    
    /** <p>A document that simultaneously contains other documents.</p> */
    public static final Resource CollectedDocument = m_model.createResource( "http://purl.org/ontology/bibo/CollectedDocument" );
    
    /** <p>A collection of Documents or Collections</p> */
    public static final Resource Collection = m_model.createResource( "http://purl.org/ontology/bibo/Collection" );
    
    /** <p>A meeting for consultation or discussion.</p> */
    public static final Resource Conference = m_model.createResource( "http://purl.org/ontology/bibo/Conference" );
    
    /** <p>A collection of legal cases.</p> */
    public static final Resource CourtReporter = m_model.createResource( "http://purl.org/ontology/bibo/CourtReporter" );
    
    /** <p>A document (noun) is a bounded physical representation of body of information 
     *  designed with the capacity (and usually intent) to communicate. A document 
     *  may manifest symbolic, diagrammatic or sensory-representational information.</p>
     */
    public static final Resource Document = m_model.createResource( "http://purl.org/ontology/bibo/Document" );
    
    /** <p>a distinct part of a larger document or collected document.</p> */
    public static final Resource DocumentPart = m_model.createResource( "http://purl.org/ontology/bibo/DocumentPart" );
    
    /** <p>The status of the publication of a document.</p> */
    public static final Resource DocumentStatus = m_model.createResource( "http://purl.org/ontology/bibo/DocumentStatus" );
    
    /** <p>An edited book.</p> */
    public static final Resource EditedBook = m_model.createResource( "http://purl.org/ontology/bibo/EditedBook" );
    
    /** <p>A written communication addressed to a person or organization and transmitted 
     *  electronically.</p>
     */
    public static final Resource Email = m_model.createResource( "http://purl.org/ontology/bibo/Email" );
    
    public static final Resource Event = m_model.createResource( "http://purl.org/ontology/bibo/Event" );
    
    /** <p>A passage selected from a larger work.</p> */
    public static final Resource Excerpt = m_model.createResource( "http://purl.org/ontology/bibo/Excerpt" );
    
    /** <p>aka movie.</p> */
    public static final Resource Film = m_model.createResource( "http://purl.org/ontology/bibo/Film" );
    
    /** <p>An instance or a session in which testimony and arguments are presented, esp. 
     *  before an official, as a judge in a lawsuit.</p>
     */
    public static final Resource Hearing = m_model.createResource( "http://purl.org/ontology/bibo/Hearing" );
    
    /** <p>A document that presents visual or diagrammatic information.</p> */
    public static final Resource Image = m_model.createResource( "http://purl.org/ontology/bibo/Image" );
    
    /** <p>A formalized discussion between two or more people.</p> */
    public static final Resource Interview = m_model.createResource( "http://purl.org/ontology/bibo/Interview" );
    
    /** <p>something that is printed or published and distributed, esp. a given number 
     *  of a periodical</p>
     */
    public static final Resource Issue = m_model.createResource( "http://purl.org/ontology/bibo/Issue" );
    
    /** <p>A periodical of scholarly journal Articles.</p> */
    public static final Resource Journal = m_model.createResource( "http://purl.org/ontology/bibo/Journal" );
    
    /** <p>A document accompanying a legal case.</p> */
    public static final Resource LegalCaseDocument = m_model.createResource( "http://purl.org/ontology/bibo/LegalCaseDocument" );
    
    /** <p>A document containing an authoritative determination (as a decree or judgment) 
     *  made after consideration of facts or law.</p>
     */
    public static final Resource LegalDecision = m_model.createResource( "http://purl.org/ontology/bibo/LegalDecision" );
    
    /** <p>A legal document; for example, a court decision, a brief, and so forth.</p> */
    public static final Resource LegalDocument = m_model.createResource( "http://purl.org/ontology/bibo/LegalDocument" );
    
    /** <p>A legal document proposing or enacting a law or a group of laws.</p> */
    public static final Resource Legislation = m_model.createResource( "http://purl.org/ontology/bibo/Legislation" );
    
    /** <p>A written or printed communication addressed to a person or organization and 
     *  usually transmitted by mail.</p>
     */
    public static final Resource Letter = m_model.createResource( "http://purl.org/ontology/bibo/Letter" );
    
    /** <p>A periodical of magazine Articles. A magazine is a publication that is issued 
     *  periodically, usually bound in a paper cover, and typically contains essays, 
     *  stories, poems, etc., by many writers, and often photographs and drawings, 
     *  frequently specializing in a particular subject or area, as hobbies, news, 
     *  or sports.</p>
     */
    public static final Resource Magazine = m_model.createResource( "http://purl.org/ontology/bibo/Magazine" );
    
    /** <p>A small reference book, especially one giving instructions.</p> */
    public static final Resource Manual = m_model.createResource( "http://purl.org/ontology/bibo/Manual" );
    
    /** <p>An unpublished Document, which may also be submitted to a publisher for publication.</p> */
    public static final Resource Manuscript = m_model.createResource( "http://purl.org/ontology/bibo/Manuscript" );
    
    /** <p>A graphical depiction of geographic features.</p> */
    public static final Resource Map = m_model.createResource( "http://purl.org/ontology/bibo/Map" );
    
    /** <p>A loose, thematic, collection of Documents, often Books.</p> */
    public static final Resource MultiVolumeBook = m_model.createResource( "http://purl.org/ontology/bibo/MultiVolumeBook" );
    
    /** <p>A periodical of documents, usually issued daily or weekly, containing current 
     *  news, editorials, feature articles, and usually advertising.</p>
     */
    public static final Resource Newspaper = m_model.createResource( "http://purl.org/ontology/bibo/Newspaper" );
    
    /** <p>Notes or annotations about a resource.</p> */
    public static final Resource Note = m_model.createResource( "http://purl.org/ontology/bibo/Note" );
    
    /** <p>A document describing the exclusive right granted by a government to an inventor 
     *  to manufacture, use, or sell an invention for a certain number of years.</p>
     */
    public static final Resource Patent = m_model.createResource( "http://purl.org/ontology/bibo/Patent" );
    
    /** <p>A public performance.</p> */
    public static final Resource Performance = m_model.createResource( "http://purl.org/ontology/bibo/Performance" );
    
    /** <p>A group of related documents issued at regular intervals.</p> */
    public static final Resource Periodical = m_model.createResource( "http://purl.org/ontology/bibo/Periodical" );
    
    /** <p>A communication between an agent and one or more specific recipients.</p> */
    public static final Resource PersonalCommunication = m_model.createResource( "http://purl.org/ontology/bibo/PersonalCommunication" );
    
    /** <p>A personal communication manifested in some document.</p> */
    public static final Resource PersonalCommunicationDocument = m_model.createResource( "http://purl.org/ontology/bibo/PersonalCommunicationDocument" );
    
    /** <p>A compilation of documents published from an event, such as a conference.</p> */
    public static final Resource Proceedings = m_model.createResource( "http://purl.org/ontology/bibo/Proceedings" );
    
    /** <p>An excerpted collection of words.</p> */
    public static final Resource Quote = m_model.createResource( "http://purl.org/ontology/bibo/Quote" );
    
    /** <p>A document that presents authoritative reference information, such as a dictionary 
     *  or encylopedia .</p>
     */
    public static final Resource ReferenceSource = m_model.createResource( "http://purl.org/ontology/bibo/ReferenceSource" );
    
    /** <p>A document describing an account or statement describing in detail an event, 
     *  situation, or the like, usually as the result of observation, inquiry, etc..</p>
     */
    public static final Resource Report = m_model.createResource( "http://purl.org/ontology/bibo/Report" );
    
    /** <p>A loose, thematic, collection of Documents, often Books.</p> */
    public static final Resource Series = m_model.createResource( "http://purl.org/ontology/bibo/Series" );
    
    /** <p>A slide in a slideshow</p> */
    public static final Resource Slide = m_model.createResource( "http://purl.org/ontology/bibo/Slide" );
    
    /** <p>A presentation of a series of slides, usually presented in front of an audience 
     *  with written text and images.</p>
     */
    public static final Resource Slideshow = m_model.createResource( "http://purl.org/ontology/bibo/Slideshow" );
    
    /** <p>A document describing a standard</p> */
    public static final Resource Standard = m_model.createResource( "http://purl.org/ontology/bibo/Standard" );
    
    /** <p>A bill enacted into law.</p> */
    public static final Resource Statute = m_model.createResource( "http://purl.org/ontology/bibo/Statute" );
    
    /** <p>A document created to summarize research findings associated with the completion 
     *  of an academic degree.</p>
     */
    public static final Resource Thesis = m_model.createResource( "http://purl.org/ontology/bibo/Thesis" );
    
    /** <p>The academic degree of a Thesis</p> */
    public static final Resource ThesisDegree = m_model.createResource( "http://purl.org/ontology/bibo/ThesisDegree" );
    
    /** <p>A web page is an online document available (at least initially) on the world 
     *  wide web. A web page is written first and foremost to appear on the web, as 
     *  distinct from other online resources such as books, manuscripts or audio documents 
     *  which use the web primarily as a distribution mechanism alongside other more 
     *  traditional methods such as print.</p>
     */
    public static final Resource Webpage = m_model.createResource( "http://purl.org/ontology/bibo/Webpage" );
    
    /** <p>A group of Webpages accessible on the Web.</p> */
    public static final Resource Website = m_model.createResource( "http://purl.org/ontology/bibo/Website" );
    
    /** <p>A seminar, discussion group, or the like, that emphasizes zxchange of ideas 
     *  and the demonstration and application of techniques, skills, etc.</p>
     */
    public static final Resource Workshop = m_model.createResource( "http://purl.org/ontology/bibo/Workshop" );
    
    public static final Resource bdarcus = m_model.createResource( "http://purl.org/ontology/bibo/bdarcus" );
    
    /** <p>masters degree in arts</p> */
    public static final Resource ma = m_model.createResource( "http://purl.org/ontology/bibo/degrees/ma" );
    
    /** <p>masters degree in science</p> */
    public static final Resource ms = m_model.createResource( "http://purl.org/ontology/bibo/degrees/ms" );
    
    /** <p>PhD degree</p> */
    public static final Resource phd = m_model.createResource( "http://purl.org/ontology/bibo/degrees/phd" );
    
    public static final Resource fgiasson = m_model.createResource( "http://purl.org/ontology/bibo/fgiasson" );
    
    /** <p>Accepted for publication after peer reviewing.</p> */
    public static final Resource accepted = m_model.createResource( "http://purl.org/ontology/bibo/status/accepted" );
    
    /** <p>Document drafted</p> */
    public static final Resource draft = m_model.createResource( "http://purl.org/ontology/bibo/status/draft" );
    
    /** <p>Document to be published</p> */
    public static final Resource forthcoming = m_model.createResource( "http://purl.org/ontology/bibo/status/forthcoming" );
    
    /** <p>Legal document</p> */
    public static final Resource legal = m_model.createResource( "http://purl.org/ontology/bibo/status/legal" );
    
    /** <p>A document that is not peer reviewed</p> */
    public static final Resource nonPeerReviewed = m_model.createResource( "http://purl.org/ontology/bibo/status/nonPeerReviewed" );
    
    /** <p>The process by which articles are chosen to be included in a refereed journal. 
     *  An editorial board consisting of experts in the same field as the author review 
     *  the article and decide if it is authoritative enough for publication.</p>
     */
    public static final Resource peerReviewed = m_model.createResource( "http://purl.org/ontology/bibo/status/peerReviewed" );
    
    /** <p>Published document</p> */
    public static final Resource published = m_model.createResource( "http://purl.org/ontology/bibo/status/published" );
    
    /** <p>Rejected for publication after peer reviewing.</p> */
    public static final Resource rejected = m_model.createResource( "http://purl.org/ontology/bibo/status/rejected" );
    
    /** <p>Unpublished document</p> */
    public static final Resource unpublished = m_model.createResource( "http://purl.org/ontology/bibo/status/unpublished" );
    
}
