/* CVS $Id: $ */
package uk.ac.bristol.dundry.vocabs; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from file:////Users/pldms/Development/Projects/2011/data.bris/dundry/src/main/resources/opmv-20101006.owl 
 * @author Auto-generated by schemagen on 26 Apr 2012 13:38 
 */
public class OPMV {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/net/opmv/ns#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>used is an abstract property to express that a process used an artifact</p> */
    public static final Property used = m_model.createProperty( "http://purl.org/net/opmv/ns#used" );
    
    /** <p>wasControlledBy is an abstract property to express that a process was controlled 
     *  by an agent.</p>
     */
    public static final Property wasControlledBy = m_model.createProperty( "http://purl.org/net/opmv/ns#wasControlledBy" );
    
    /** <p>wasDerivedFrom is an abstract property to express that an artifact was derived 
     *  from another artifact.</p>
     */
    public static final Property wasDerivedFrom = m_model.createProperty( "http://purl.org/net/opmv/ns#wasDerivedFrom" );
    
    /** <p>wasEncodedBy is an object property to express that an artifact is encoded 
     *  by another artifact. The property is useful for expressing the relationship 
     *  between the data and the file encoding the data.</p>
     */
    public static final Property wasEncodedBy = m_model.createProperty( "http://purl.org/net/opmv/ns#wasEncodedBy" );
    
    /** <p>wasEndedAt is an object property to express that a process was finished at 
     *  a specific time instant. The property chain defines that all processes, that 
     *  were performed during a specific time period which ended at a specific instant, 
     *  were actually finished at that specific time instant.</p>
     */
    public static final Property wasEndedAt = m_model.createProperty( "http://purl.org/net/opmv/ns#wasEndedAt" );
    
    /** <p>wasGeneratedAt is an object property to express that an artifact was generated 
     *  at a specific time instant. This property is very similar to dct:created. 
     *  Note that in a very fine-grained case the time when an artifact was generated 
     *  might not be the same as the time when the process producing that artifact 
     *  finished.</p>
     */
    public static final Property wasGeneratedAt = m_model.createProperty( "http://purl.org/net/opmv/ns#wasGeneratedAt" );
    
    /** <p>wasGeneratedBy is an abstract property to express that an artifact was generated 
     *  by a process.</p>
     */
    public static final Property wasGeneratedBy = m_model.createProperty( "http://purl.org/net/opmv/ns#wasGeneratedBy" );
    
    /** <p>wasPerformedAt is an object property to express that a process is performed 
     *  either at a specific time instant or during a specific time interval.</p>
     */
    public static final Property wasPerformedAt = m_model.createProperty( "http://purl.org/net/opmv/ns#wasPerformedAt" );
    
    /** <p>wasPerformedBy is an object property to express that a process was performed 
     *  by another process. It is a sub-property of wasControlledBy.</p>
     */
    public static final Property wasPerformedBy = m_model.createProperty( "http://purl.org/net/opmv/ns#wasPerformedBy" );
    
    /** <p>wasStartedAt is an object property to express that a process is started at 
     *  a specific time instant. The property chain defines that all processes, that 
     *  were performed during a specific time period which began at a specific instant, 
     *  were actually started at that specific time instant.</p>
     */
    public static final Property wasStartedAt = m_model.createProperty( "http://purl.org/net/opmv/ns#wasStartedAt" );
    
    /** <p>wasTriggeredBy is an abstract property to express that a process was triggerred 
     *  by another process.</p>
     */
    public static final Property wasTriggeredBy = m_model.createProperty( "http://purl.org/net/opmv/ns#wasTriggeredBy" );
    
    /** <p>wasUsedAt is an object property to express that an artifact was used at a 
     *  specific time instant. An artifact might not be used at the starting time 
     *  of the process that actually consumed it. Hence, we provide a different time-related 
     *  property to express when an artifact was used.</p>
     */
    public static final Property wasUsedAt = m_model.createProperty( "http://purl.org/net/opmv/ns#wasUsedAt" );
    
    /** <p>withRespectOf is an object property to associate a time instant at which an 
     *  artifact was used or generated with the process that used or generated that 
     *  artifact. At a very fine-grained distinction, the time when an artifact was 
     *  used or generated might not be exactly the same as the starting or ending 
     *  time of the process in which the artifact was involved. The related properties 
     *  opmv:wasUsedAt and opmv:wasGeneratedAt can be used as shortcuts to express 
     *  time-related information about an artifact. The property opmv:wasUsedAt is 
     *  only used when users want to express precisely in which process an artifact 
     *  was used or generated. It can be omitted in most cases.</p>
     */
    public static final Property withRespectOf = m_model.createProperty( "http://purl.org/net/opmv/ns#withRespectOf" );
    
    /** <p>Agent is a contextual entity acting as a catalyst of a process, enabling, 
     *  facilitating, controlling, or affecting its execution.</p>
     */
    public static final Resource Agent = m_model.createResource( "http://purl.org/net/opmv/ns#Agent" );
    
    /** <p>Artifact is a general concept that represents immutable piece of state, which 
     *  may have a physical embodiment in a physical object, or a digital representation 
     *  in a computer system.</p>
     */
    public static final Resource Artifact = m_model.createResource( "http://purl.org/net/opmv/ns#Artifact" );
    
    /** <p>Process refers to an action or series of actions performed on or caused by 
     *  artifacts, and resulting in new artifacts.</p>
     */
    public static final Resource Process = m_model.createResource( "http://purl.org/net/opmv/ns#Process" );
    
}
