/* CVS $Id: $ */
package uk.ac.bristol.dundry.vocabs; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from file:////home/pldms/Development/Projects/2012/data.bris/dundry/src/main/resources/common/vocabs/repository.ttl 
 * @author Auto-generated by schemagen on 09 Oct 2012 17:17 
 */
public class RepositoryVocab {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://vocab.bris.ac.uk/data/repository#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The base directory for file storage associated with this deposit.</p> */
    public static final Property base_directory = m_model.createProperty( "http://vocab.bris.ac.uk/data/repository#base-directory" );
    
    /** <p>The individual who made this deposit.</p> */
    public static final Property depositor = m_model.createProperty( "http://vocab.bris.ac.uk/data/repository#depositor" );
    
    /** <p>A project (typically a research project) associated with this item.</p> */
    public static final Property project = m_model.createProperty( "http://vocab.bris.ac.uk/data/repository#project" );
    
    /** <p>The state of a deposit, for example in progress, published.</p> */
    public static final Property state = m_model.createProperty( "http://vocab.bris.ac.uk/data/repository#state" );
    
}
